/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i Common/datatypes.h -c RevelesDBusAdaptor -a reveles_dbus_adaptor.h:reveles_dbus_adaptor.cpp revelesdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef REVELES_DBUS_ADAPTOR_H
#define REVELES_DBUS_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "Common/datatypes.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.reveles.RevelesCoreInterface
 */
class RevelesDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.reveles.RevelesCoreInterface")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.reveles.RevelesCoreInterface\">\n"
"    <signal name=\"commQuery\"/>\n"
"    <signal name=\"requestCurrentLocation\"/>\n"
"    <signal name=\"requestMapUpdate\"/>\n"
"    <signal name=\"setDestination\">\n"
"      <annotation value=\"GPSCoord\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"(dd)\" name=\"gpsc\"/>\n"
"    </signal>\n"
"    <signal name=\"AutoMapUpdate\">\n"
"      <annotation value=\"GPSCoord\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"(dd)\" name=\"gpsc\"/>\n"
"    </signal>\n"
"    <signal name=\"setMapUpdateInterval\">\n"
"      <arg direction=\"out\" type=\"i\" name=\"milliseconds\"/>\n"
"    </signal>\n"
"    <signal name=\"commResponse\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"good\"/>\n"
"    </signal>\n"
"    <signal name=\"locationUpdate\">\n"
"      <annotation value=\"GPSCoord\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"(dd)\" name=\"loc\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    RevelesDBusAdaptor(QObject *parent);
    virtual ~RevelesDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void AutoMapUpdate(GPSCoord gpsc);
    void commQuery();
    void commResponse(bool good);
    void locationUpdate(GPSCoord loc);
    void requestCurrentLocation();
    void requestMapUpdate();
    void setDestination(GPSCoord gpsc);
    void setMapUpdateInterval(int milliseconds);
};

#endif
