/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i ../RPi/Common/datatypes.h -c RevelesDBusCoreAdaptor -a reveles_dbus_core_adaptor.h:reveles_dbus_core_adaptor.cpp revelesdbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "reveles_dbus_core_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RevelesDBusCoreAdaptor
 */

RevelesDBusCoreAdaptor::RevelesDBusCoreAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RevelesDBusCoreAdaptor::~RevelesDBusCoreAdaptor()
{
    // destructor
}

